// <auto-generated />
namespace recollection.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class remove_image_requirement : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_image_requirement));
        
        string IMigrationMetadata.Id
        {
            get { return "201503221833524_remove_image_requirement"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
